# Generated by Django 3.2.5 on 2022-08-09 17:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drzData', '0003_auto_20220728_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachgesprek',
            name='cgs_ElektraMeter',
        ),
        migrations.RemoveField(
            model_name='coachgesprek',
            name='cgs_IsKokenMetDeksel',
        ),
        migrations.AddField(
            model_name='coachgesprek',
            name='cgs_CVLeeftijd',
            field=models.IntegerField(blank=True, help_text='Hoeveel jaren oud is de cv ketel', null=True, verbose_name='Leeftijd cv ketel'),
        ),
        migrations.AddField(
            model_name='coachgesprek',
            name='cgs_Is_BoilerAanw',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is er een boiler aanwezig'),
        ),
        migrations.AddField(
            model_name='coachgesprek',
            name='cgs_Is_DrogerAanw',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is er een wasdroger aanwezig?'),
        ),
        migrations.AddField(
            model_name='coachgesprek',
            name='cgs_Is_GeiserAanw',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is er een geiser aanwezig'),
        ),
        migrations.AddField(
            model_name='coachgesprek',
            name='cgs_Is_WarmteNet',
            field=models.BooleanField(blank=True, help_text='Is de woning aangesloten op een warmtenet?', null=True, verbose_name='Aangesloten op wartenet'),
        ),
        migrations.AddField(
            model_name='coachgesprek',
            name='cgs_LeeftKoelk',
            field=models.IntegerField(blank=True, null=True, verbose_name='Leeftijd koelkast'),
        ),
        migrations.AddField(
            model_name='coachgesprek',
            name='cgs_TypeDroger',
            field=models.CharField(blank=True, choices=[('C', 'Condens'), ('W', 'Warmtepomp'), ('A', 'Luchtafvoer')], max_length=1, null=True, verbose_name='Type wasdroger'),
        ),
        migrations.AddField(
            model_name='coachgesprek',
            name='cgs_TypeGasMeter',
            field=models.CharField(blank=True, choices=[('G', 'Analoog'), ('D', 'Digitaal (niet slim)'), ('S', 'Slimme meter')], help_text='Wat voor gasmeter heeft u geconstateerd?', max_length=1, null=True, verbose_name='Gasmeter'),
        ),
        migrations.AddField(
            model_name='coachgesprek',
            name='cgs_TypeMeterWarmteNet',
            field=models.CharField(blank=True, choices=[('Vd', 'Verdamping'), ('Jo', 'Joule'), ('M3', 'Kubieke meter')], max_length=2, null=True, verbose_name='Warmtenet type meter'),
        ),
        migrations.AddField(
            model_name='coachgesprek',
            name='cgs_Verhuurder',
            field=models.TextField(blank=True, help_text='Naam van verhuurder of woningbouwcooperatie', max_length=85, null=True, verbose_name='Naam verhuurder'),
        ),
        migrations.AddField(
            model_name='coachgesprek',
            name='cgs_WarmteNet',
            field=models.CharField(blank=True, choices=[('NAlm', 'Nuon Warmte Almere'), ('NAms', 'Nuon Warmte Amsterdam'), ('NDui', 'Nuon Warmte Duiven – West ervoort'), ('NLei', 'Nuon Warmte Leiden'), ('EAme', 'Essent Warmte Amernet'), ('EnDH', 'Eneco warmte Den Haag – Ypenburg'), ('EEns', 'Essent Warmte Enschede'), ('WHel', 'Wamob Helmond'), ('SVPu', 'SV Purmerend'), ('EnRo', 'Eneco Warmte Rotterdam'), ('EnUt', 'Eneco Warmte Ut recht – St ad'), ('EnLR', 'Eneco Warmte Ut recht – Leidsche Rij n'), ('EnNw', 'Eneco Warmte Ut recht – Nieuwegein')], help_text='Op welk warmtenet is het huis aangesloten?', max_length=4, null=True, verbose_name='Warmtenet'),
        ),
        migrations.AlterField(
            model_name='coachgesprek',
            name='cgs_BespaarAdviesTekst',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Bespaar advies'),
        ),
        migrations.AlterField(
            model_name='coachgesprek',
            name='cgs_CVTemperatuur',
            field=models.CharField(blank=True, choices=[('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('90', '90')], help_text='Op wat voor water temperatuur staat de CV ketel ingestel', max_length=2, null=True, verbose_name='Temperatuur cv ketel'),
        ),
        migrations.AlterField(
            model_name='coachgesprek',
            name='cgs_TypeElektraMeter',
            field=models.CharField(blank=True, choices=[('G', 'Analoog'), ('D', 'Digitaal (niet slim)'), ('S', 'Slimme meter (AMR-meter)')], help_text='Wat voor elektrameter heeft u geconstateerd?', max_length=1, null=True, verbose_name='Elektrameter'),
        ),
        migrations.AlterField(
            model_name='coachgesprek',
            name='cgs_TypeThermostaat',
            field=models.CharField(blank=True, choices=[('G', 'Standaard'), ('S', 'Met dag nacht stand'), ('P', 'Programmeerbaar'), ('Z', 'Zelflerend'), ('W', 'Weersafhankelijk')], max_length=1, null=True, verbose_name='Type thermostaat'),
        ),
    ]
