# Generated by Django 3.2.5 on 2022-08-09 23:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('drzData', '0005_alter_coachgesprek_cgs_verhuurder'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachgesprek',
            name='cgs_StatusGesprek',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('A', 'Aangemeld'), ('B', 'Gebeld / Ingeplanned'), ('E', 'BevestigingsE-mail verstuurd'), ('G', 'Gesprek geschied'), ('A', 'Advies opgemaakt'), ('F', 'Followup ingeplanned'), ('V', 'Bevestiging followup verstuurd')], help_text='De verschillende statussen in het traject van de coachgesprek', max_length=13, null=True, verbose_name='Status van Coachgesprek'),
        ),
        migrations.AlterField(
            model_name='coachgesprek',
            name='cgs_TypeRadiatorknop',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('G', 'Standaard'), ('T', 'Thermostaat')], help_text='Type radiatorknoppen aanwezig in huis?', max_length=3, null=True, verbose_name='Type radiatorknop'),
        ),
    ]
