# Generated by Django 3.2.15 on 2022-10-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drzData', '0007_auto_20221021_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='vraag',
            name='vrg_DatVastlegging',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tijdstip van notatie'),
        ),
    ]
