# Generated by Django 3.2.15 on 2023-01-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drzData', '0008_vraag_vrg_datvastlegging'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='cnt_EMail',
            field=models.CharField(blank=True, help_text='Mobiel, Telefoon, E-mail, Facebook, enz.', max_length=85, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='contact',
            name='cnt_HuisNr',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Huisnummer'),
        ),
        migrations.AddField(
            model_name='contact',
            name='cnt_HuisNrToev',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Toevoeging'),
        ),
        migrations.AddField(
            model_name='contact',
            name='cnt_Plaats',
            field=models.CharField(blank=True, max_length=85, null=True, verbose_name='Plaats'),
        ),
        migrations.AddField(
            model_name='contact',
            name='cnt_PostCd',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Postcode'),
        ),
        migrations.AddField(
            model_name='contact',
            name='cnt_Straat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Straat'),
        ),
        migrations.AddField(
            model_name='contact',
            name='cnt_Telefoon',
            field=models.CharField(blank=True, help_text='Mobiel, Telefoon, E-mail, Facebook, enz.', max_length=85, null=True, verbose_name='Telefoon'),
        ),
        migrations.AddField(
            model_name='contact',
            name='cnt_type',
            field=models.CharField(blank=True, choices=[('W', 'Woonadres'), ('B', 'Bezoekadres'), ('A', 'Afleveradres'), ('V', 'Verblijfadres')], default='W', max_length=1, null=True, verbose_name='Type adres'),
        ),
    ]
